# The base Apache Knox image, see https://github.com/pfisterer/apache-knox-docker for details
image:
  repository: farberg/apache-knox-docker
  tag: 1.5.0
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  path: "/"
  hosts: []
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local


knox:
  users:
    admin:
      pw: "admin-password"
    sam:
      pw: "sam-password"
    tom:
      pw: "tom-password"

  servicetype: ClusterIP

  hadoop:
    nameNodeUrl: "hdfs://nn:9000/webhdfs"
    resourceManagerUrl: "http://rm:8088/ws"
    webHdfsUrl: "http://nn:50070/webhdfs"
    hdfsUIUrl: "http://nn:50070/"
    yarnUIUrl: "http://yarn-ui:8088"

  gateway:
    logLevel: "DEBUG"

  ldap:
    logLevel: "INFO"
